### ISSUE TITLE
Baskerville version 2

### ISSUE THREAD

**Issue by saraiva** [andersnoren/baskerville#1]
Hi Anders,

is the new Baskerville 2 theme only available on wordpress.com? If I look within my wordpress search menu I only find the previous version.

Best regards, Pedro

**Comment by andersnoren** [comment]
@saraiva Baskerville 2 is not a new version of Baskerville, but simply the WordPress.com version. It's developed by the Automattic theme wranglers based on the design of Baskerville, but the code is completely separate.

If you host your site on WordPress.com, I'd recommend you to use Baskerville 2. If not, I'd recommend the original Baskerville.

**Comment by saraiva** [comment]
ok, thanks for the quick reply. I was looking for a theme with site editor capabilities and spotted the version 2.
I'm trying Norrsken now.
